[package]
name = "origis-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2"
pest_derive = "2.1.0"
pest-ast = "0.3.3"
from-pest = "0.3.1"
